// AUTO-GENERATED by scripts/set-firebase-config.mjs — DO NOT EDIT.
// Values come from environment variables at build time.
import {FirebaseOptions} from 'firebase/app';

const firebaseConfig: FirebaseOptions = {
    apiKey: '',
    authDomain: '',
    projectId: '',
    storageBucket: '',
    messagingSenderId: '',
    appId: '',
};

export {firebaseConfig};
