name: NodeJS with Webpack
on: [push]
jobs:
  strategy:
    matrix:
      ubuntu-version: [ubuntu-latest]
      node-version: [18.x]
  setup:
    runs-on: ${{ matrix.ubuntu-version }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      run: npm install
  lint:
    runs-on: ${{ matrix.ubuntu-version }}
    needs: setup
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Restore node_modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
    - name: lint
      run: npm run lint
