name: NodeJS with Webpack
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Jest
      run: npm run jest:ci
    - name: Build
      run: npm run build
  cypress-run:
    runs-on: ubuntu-latest
#    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Start
        run: npm start
      - name: Cypress component
        run: npm run cypress:component
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Download the build folder
#        uses: actions/download-artifact@v3
#        with:
#          name: build
#          path: build
#      - name: Cypress run component
#        uses: cypress-io/github-action@v6
#        with:
#          start: npm start && npm run cypress:component
#          browser: chrome
